"use client";

import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';
import Navbar from './Navbar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en">
            <body style={inter.style}>
                <header>
                    <Navbar />
                </header>

                <main>
                    {children}
                </main>
            </body>
        </html>
    );
}
